renew backend DEV Pipe

diff --git a/.github/workflows/backend.yaml b/.github/workflows/backend.yaml
--- a/.github/workflows/backend.yaml
+++ b/.github/workflows/backend.yaml
@@ -30,8 +30,8 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-      with:
-        fetch-depth: 2
+      # with:
+      #   fetch-depth: 2
     # - name: Check / set env Prod
     #   if: ${{ github.ref == 'refs/heads/main' }}
     #   run: |  
@@ -50,23 +50,34 @@ jobs:
     #         if [ -s diff ];then echo "DIFF=true" >> $GITHUB_ENV; else echo "DIFF=false" >> $GITHUB_ENV; fi
     #         echo ${{ env.DIFF }}
     
-    - name: Copy Docker Build
-      # if: ${{ env.DIFF == 'true' }}
-      run: |
-            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/requirements.txt ./deploy/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}build
-    - name: Build Image
-      # if: ${{ env.DIFF == 'true' }}
-      run: |
-            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
-            ssh docker-agent <<-'EOF2'
-                cd ${{ secrets.BASE_DIR_APP }}build/ \
-                && sudo iptables -t mangle -F PREROUTING \
-                && docker build . -t dj:latest \
-                && sudo iptables-restore < /etc/iptables/rules.v4 \
-                && docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} down \
-                && docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} up -d
-            EOF2
-            EOF
+    # - name: Copy Docker Build
+    #   # if: ${{ env.DIFF == 'true' }}
+    #   run: |
+    #         sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/requirements.txt ./deploy/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}build
+    # - name: Build Image
+    #   # if: ${{ env.DIFF == 'true' }}
+    #   run: |
+    #         sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
+    #         ssh docker-agent <<-'EOF2'
+    #             cd ${{ secrets.BASE_DIR_APP }}build/ \
+    #             && sudo iptables -t mangle -F PREROUTING \
+    #             && docker build . -t dj:latest \
+    #             && sudo iptables-restore < /etc/iptables/rules.v4 \
+    #             && docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} down \
+    #             && docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} up -d
+    #         EOF2
+    #         EOF
+
+    - uses: pmorelli92/github-container-registry-build-push@2.0.0
+      name: Build and Publish latest service image
+      with:
+        github-push-secret: ${{secrets.GITHUB_TOKEN}}
+        docker-image-name: dj:
+        docker-image-tag: ${{ needs.version.outputs.vID }} # optional
+        dockerfile-path: ./DockerfileFrontend # optional
+        # build-context: ./backend/ # optional
+
+
 
   Deploy:
     runs-on: ubuntu-latest
@@ -87,29 +98,46 @@ jobs:
       run: |
             echo "APP_ENV=DEV" >> $GITHUB_ENV
     
-    - name: Prepare Backend
-      run: |
-            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
-            mkdir -p ${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }}/swd
-            EOF
+    # - name: Prepare Backend
+    #   run: |
+    #         sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
+    #         mkdir -p ${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }}/swd
+    #         EOF
 
+    # - name: Copy Files
+    #   run: |
+    #         sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }}/swd
+
+    # - name: Release Backend && Restart
+    #   run: |
+    #         sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} <<-EOF
+    #         ssh docker-agent <<-'EOF2'
+    #           docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} down
+    #         EOF2
+    #         cd ${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }} \
+    #         && rm -rf bak || echo "bak not found" \
+    #         && mv prd bak || echo "prd not found" \
+    #         && mv swd prd || echo "swd not found" \
+    #         && cd prd \
+    #         && ln -s ../.env .env \
+    #         && ssh docker-agent <<-'EOF3'
+    #           docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} up -d
+    #         EOF3
+    #         EOF
     - name: Copy Files
       run: |
-            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }}/swd
-
-    - name: Release Backend && Restart
+            sshpass -p "${{ secrets.SSH_PAS }}" rsync -a --rsh="ssh -o StrictHostKeyChecking=no" ./backend/ ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }}/${GITHUB_SHA}/
+   
+    - name: Release Backend
       run: |
-            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} <<-EOF
-            ssh docker-agent <<-'EOF2'
+            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
+            cd ${{ secrets.BASE_DIR_APP }}${{ env.DIR }} \
+            && ssh docker-agent <<-'EOF2'
               docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} down
             EOF2
-            cd ${{ secrets.BASE_DIR_APP }}${{ env.APP_ENV }} \
-            && rm -rf bak || echo "bak not found" \
-            && mv prd bak || echo "prd not found" \
-            && mv swd prd || echo "swd not found" \
-            && cd prd \
-            && ln -s ../.env .env \
-            && ssh docker-agent <<-'EOF3'
+            && ln -s ../.env ./prd/.env \
+            && ln -sfn ${GITHUB_SHA} prd
+            && ssh docker-agent <<-'EOF2'
               docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app_compose.yaml --env-file ${{ secrets.BASE_DIR_OPS }}config/.env_app_${{ env.APP_ENV }} up -d
-            EOF3
+            EOF2
             EOF
